SatisfactoryModLoader/SatisfactoryModLoader.cpp, SatisfactoryModLoader/util/Configuration.h
With the current method you're checking if a value is `NULL` which is also `false`. So if a value inside the config is `false` it always fallbacks to the default value.
This pull request introduces an `defaultValue` parameter, which the method fallbacks to if the requested key cannot be found, writes the selected `defaultValue` to the config and returns it.
=> Use default values when reading config

Source/FactoryGame/Private/Buildables/FGBuildablePipeBase.cpp, Source/FactoryGame/Private/FGRecipe.cpp, Source/FactoryGame/Private/FGSchematic.cpp, Source/FactoryGame/Private/Resources/FGItemDescriptor.cpp, Source/FactoryGame/Public/FGPipeConnectionComponent.h, Source/FactoryGame/Public/Resources/FGResourceNode.h, Source/SML/mod/BlueprintLibrary.cpp, Source/SML/mod/BlueprintLibrary.h
Commented mInstancedSplineComponent in the constructor AFGBuildablePipeBase out, it crashes the game on startup.
Added inClass nullptr checks in FGSchematic, FGRecipe and FGItemDescriptor to prevent the editor from crashing when one is provided.
Added function bodies for EDITOR ONLY Icon values on FGItemDescriptor.
PipeConnection Inventory variables set to BPReadOnly/BPReadWrite.
ResourceNode protected variables set to BPReadOnly/BPReadWrite.
Added BP Function to get the currently used DevelopmentModeSetting.
=> Fixes for Editor and Game Crash

Config/DefaultEngine.ini
Vulkan needs to be added to the Windows Target List or shaders won't be cooked for it, causing materials and textures to fallback to defaults.
=> Update DefaultEngine.ini to add Vulkan target

Plugins/SML/Source/SML/Private/Registry/ModContentRegistry.cpp, Plugins/SML/Source/SML/Public/Registry/ModContentRegistry.h
Added checks to prevent removal of any object that originated in the FactoryGame project, regardless of whether they are registered. 
Added new warning message to display any occurrences of this.
=> Prevent removal of FactoryGame Recipes and Schematics

Plugins/SML/Source/SML/Private/Configuration/Properties/WidgetExtension/CP_Integer.cpp
Prevents the [EnumName]_MAX value from showing in mod configs that use the int-based enum drop-down. 
Before: https://i.imgur.com/boskkUV.jpeg
After: https://i.imgur.com/vWYWYgr.jpeg
If there is a better method of doing this, I'm all for it. This was the only way I could think of that didn't involve string matching.
=> Remove Enum MAX from Configs

Plugins/SML/Source/SML/Public/Patching/NativeHookManager.h
Add SML_API to LogNativeHookManager needed for MrHid6 to build FicsitFarming for linux.
EDIT: PR is being gutted to be just the SML_API change for MrHid6, Updating this soon
Originally, This contained an attempted (incorrect) fix for dependencies on linux and a change needed for MrHid6. It is now just the change for MrHid6
=> Add SML_API to LogNativeHookManager

Plugins/SML/Source/SML/Private/Util/RuntimeBlueprintFunctionLibrary.cpp, Plugins/SML/Source/SML/Public/Util/RuntimeBlueprintFunctionLibrary.h
Add bool to optionally set hooks from BP to have the offset set to Start instead of always being Return. Backwards compatible with existing usage of BindOnBPFunction.
=> Add HookOffsetStart bool to BindOnBPFunction

Plugins/SML/Source/SML/Public/Patching/BlueprintHookHelper.h
See this conversation in `#cpp-help` on the Discord: https://discord.com/channels/555424930502541343/862002356626128907/1024907614817112095
=> Remove build-erroring unused Prop field

Mods/SML/Source/SML/Private/Registry/ModContentRegistry.cpp, Mods/SML/Source/SML/Public/Registry/ModContentRegistry.h
In the `IsDescriptorFilteredOut()` function, add additional checks to filter out item descriptors depending on their resource form. Without this change, the `IncludeNonSolid` flag does absolutely nothing. Also filter out any non-subclasses of `UFGItemDescriptor`, which shouldn't have been registered in the item registry to begin with.
=> ModContentRegistry: Filter item descriptor by resource form

Mods/SML/Source/SML/Public/Patching/NativeHookManager.h
Looks like the hook invoker for global functions has a typo which prevents hooking global functions with non-void return. There are two instances of `.getResult()` that should be `.GetResult()`.
=> NativeHookManager.h: Fix typo in function name

Mods/Alpakit/Templates/CPPAndBlueprintBlank/Source/PLUGIN_NAME/PLUGIN_NAME.Build.cs
The "AssetRegistry" dependency was listed multiple times in the list of dependencies. Keep only the first instance.
=> fix: Drop duplicate entry in Alpakit C++ template deps

Mods/SML/Source/SML/Private/SessionSettings/SessionSettingsManager.cpp, Mods/SML/Source/SML/Public/SessionSettings/SessionSettingsManager.h
When trying to retrieve the float value of a session setting that does not exist, the game crashes because SML asserts on something involving variant type traits:
```
Assertion failed: (Type == TVariantTraits<T>::GetType()) || ((TVariantTraits<T>::GetType() == EVariantTypes::UInt8) && (Type == EVariantTypes::Enum))
```
This is because the fallback value passed to the `FVariant` constructor template is a literal `0`, whose type is `int`:
```cpp
return GetOptionValue(cvar, FVariant(0)).GetValue<float>();
/* This: ~~~~~~~~~^~ */
```
Using (integer) literals for template argument deduction is troublesome because the deduced template type is not visible by default. Given that requiring callers to cast literals is hideous and error-prone, use some funny template shenanigans to prevent template …
=> Fix problems involving inexistent session settings

Config/DefaultDeviceProfiles.ini, Config/DefaultEditor.ini, Config/DefaultEngine.ini
Just do as UE says:
Found a deprecated ini section name in SomeFile.ini.
Search for [/Script/Engine.TextureLODSettings] and
replace with [GlobalDefaults DeviceProfile]
=> Replace deprecated sections in .ini files

Mods/SML/Source/SML/Private/SessionSettings/SessionSettingsSubsystem.cpp, Mods/SML/Source/SML/Public/SessionSettings/SessionSettingsManager.h, Mods/SML/Source/SML/Public/SessionSettings/SessionSettingsSubsystem.h
Added Server and Client RPCs so a joining client can ask for existing Session Settings from the Server and the server can send them back.
=> Fix for Session Settings not syncing

Mods/SML/Source/SML/Public/Patching/NativeHookManager.h
I thought this was already merged or in a PR somewhere... i guess not.
=> NativeHookManager.h: Fix compile issue with Linux Server

Mods/AccessTransformers/Source/AccessTransformers.ubtplugin/Hooking/AHookingEntrypoint.cs, Mods/AccessTransformers/Source/AccessTransformers.ubtplugin/Types/AccessTransformers.cs
Access transformers can randomly fail builds. Looking into this, the accessors generated by the build tool appear multiple times in the file:
While I'm not sure of the exact cause, I observed that InsertCodeForClass was being called multiple times, and the accessors in the list kept piling up. I end up fixing this by clearing the list when the AT gets rescanned and also filtering to entries that haven't been used. I am not sure if this is correct behavior, but it results in my mod building without issue (and I had Discord user `d4rkl0rd` test my patch as well).
Unanswered questions:
- How does this behave with multiple mods? How does this behave with multiple mods with the same AT?
- I am relatively new to this scene so I am not able to answer how this will behave with multiple mods (as I …
=> Fix duplicates in access transformers

Source/FactoryGame/Private/Buildables/FGBuildable.cpp
Looking at the game's binaries, the root component of buildables has to default to static mobility. Otherwise, pre-placed buildings do not work properly in the editor.
The pre-placed buildings in ExampleLevel should no longer be stuck at 0 (which is inside the starting cube), but the level needs to be resaved.
=> FGBuildable.cpp: Fix root component mobility

Mods/SML/Source/SML/Private/Module/GameWorldModule.cpp
SML will crash if a mod references a null mod subsystem class in a GameWorldModule. Add an editor check to catch this.
=> Validate ModSubsystems in GameWorldModule

Mods/SML/Source/SML/Private/Tooltip/ItemTooltipSubsystem.cpp
When adding a tooltip widget using the SML provider it currently places the widget in the mTitle overlay and not at the bottom of the vertical box under the item description.
This change fixes that.
=> fix: Fixed the SML Item tooltip.

Mods/SML/Source/SML/Public/Patching/NativeHookManager.h
For some reason, `SUBSCRIBE_METHOD_EXPLICIT_VIRTUAL_AFTER` was the only "explicit" macro in this header. Add the remaining macros, based on the corresponding "non-explicit" macros.
=> NativeHookManager: Add more "explicit" hook macros

Mods/Alpakit/Source/Alpakit/Private/AlpakitModEntryList.cpp, Mods/SMLEditor/SMLEditor.uplugin
Instead of having a hardcoded list of editor-only mods to not show in the Alpakit mod list, allow mods to set an "EditorOnly" bool property in the .uplugin to hide them in Alpakit.
=> Alpakit: Generalise hiding editor-only mods

Mods/SML/Source/SML/Private/Registry/ModContentRegistry.cpp, Mods/SML/Source/SML/Public/Registry/ModContentRegistry.h
Currently SML lets mods register their content, content registration automatically traverses dependencies from research tree > schematic > recipe > item, this way if a mod for example adds a new recipe for `iron plates` it will be registered as if the mod owns it
After that SML will do a pass with all schematics from the base game, and it will force update anything referenced by these base game schematics to also be considered as part of the base game
This causes an issue when you set a mod schematic as an unlock dependency for an base game schematic, for example if a mod adds an milestone schematic that gives earlier access to pipes, and that mod wants to make sure that when that milestone is obtained the player can also buy the clear pipes variant, the mod would need to CDO edit the …
=> Dont mark content as BuiltIn if its not from the basegame

Mods/Alpakit/Source/Alpakit/Private/AlpakitReleaseWidget.cpp, Mods/Alpakit/Source/Alpakit/Private/AlpakitStyle.cpp
Update for PR 287 to use an icon instead of text for the open mod folder button, similar to the alerts for game version targeting.
=> Changed the open folder from text to an icon.

Mods/SML/Source/SML/Private/SMLModule.cpp, Mods/SML/Source/SML/Private/SatisfactoryModLoader.cpp, Mods/SML/Source/SML/Public/SatisfactoryModLoader.h
Added ExecCmds to SML which can be used in a Shipping build. Won't be run on non-Shipping builds.
=> Add ExecCmds functionality for Shipping builds

Mods/SML/Source/SML/Private/Command/ChatCommandInstance.cpp, Mods/SML/Source/SML/Private/Command/SMLCommands/HelpCommandInstance.cpp, Mods/SML/Source/SML/Private/Command/SMLCommands/InfoCommandInstance.cpp, Mods/SML/Source/SML/Private/Command/SMLCommands/PlayerListCommandInstance.cpp, Mods/SML/Source/SML/Public/Command/ChatCommandInstance.h
#332 revealed that UE will preserve data in BP assets when making this switch. BP commands auto-update but C++ needs switching to LOCTEXT/NSLOCTEXT
=> Fix #191 by switching chat command `Usage` to FText.

Mods/SML/Source/SML/Private/ModLoading/ModLoadingLibrary.cpp
Oftentimes, we only get the log files, no `.smmprofile` or any other file.
Sometimes we can't even contact the original poster to ask their mod versions.
Most of the times we can, but we can save the round-trip time of asking and getting answers.
Example Output:
```
(...)
[2025.01.31-00.43.35:843][  0]LogOnlineIntegration: Initialized 'Epic' online backend
[2025.01.31-00.43.35:843][  0]LogCommonUser: HandleNetworkConnectionStatusChanged(Context:Platform, ServiceName:, OldStatus:NotConnected, NewStatus:NotConnected)
[2025.01.31-00.43.35:843][  0]LogCommonUser: HandleNetworkConnectionStatusChanged(Context:CrossPlay, ServiceName:, OldStatus:NotConnected, NewStatus:Connected)
[2025.01.31-00.43.35:846][  0]LogSatisfactoryModLoader: Display: List of loaded mods:
[2025.01.31-00.43.35:846][ …
```
=> Log mod versions while initializing

Mods/AccessTransformers/Source/AccessTransformers/Private/AccessTransformersSubsystem.cpp, Mods/AccessTransformers/Source/AccessTransformers/Public/AccessTransformersSubsystem.h
It didn't look like there were any other struct specifiers we'd want to use, so I went with a solution that just uses BlueprintType https://dev.epicgames.com/documentation/en-us/unreal-engine/struct-specifiers?application_version=4.27 .
I had to use `FUStructReference ` instead of `FStructReference ` because `FStructReference ` already exists in UE code.
=> Add BlueprintType Access Transformer option

Mods/SML/Source/SML/Private/Kismet/BlueprintAssetHelperLibrary.cpp
A mount point like `GameShow` (from a mod) should not be treated as if it were owned by the game.
@budak7273 can you please test this? Thanks in advance.
=> Fix mapping object paths to plugins

Source/FactoryGame/Private/FGResearchTree.cpp
Quoting Mircea:
> The whole point of validation is to safely validate the data, not
> crash if it's invalid.
Replace `CastFieldChecked` with `CastField` to avoid asserting when performing data validation. Furthermore, add some NULL checks, some to handle `NodeDataStructProperty` being NULL, and another to avoid problems if `SchematicStructProperty` happens to be NULL.
=> FGResearchTree: Do not crash/assert when reflecting

Mods/SML/Source/SML/Private/Patching/WidgetBlueprintHookManager.cpp, Mods/SML/Source/SML/Public/Patching/WidgetBlueprintHookManager.h
Previously, when the parent type is "Indirect (Child)", you could only choose the immediate parents of the widget variables for the widget to attach the new widget to. Now you can choose the grandparents too.
For instance, if the widget looks like this,
there was no (easy) way to add a widget to the vertical box or the overlay.
With this pull request, you can choose them like this.
=> Ability to climb up the parent tree for widget blueprint hooking

Mods/SML/Source/SML/Public/Module/GameInstanceModule.h, Mods/SML/Source/SML/Public/Patching/DeprecatedLegacyHookingTypes.h
Blueprint SCS hooks were clearing existing data. The property needed to use the UBlueprintSCSHookData class to maintain existing data.
UE doesn't allow a property to use a deprecated class despite the error message saying you just have to mark it deprecated. The only way I could actually get it to compile was with [[deprecated("This property uses a deprecated class.")]] which is a standard cpp thing, but doing so prevents the property from showing in the editor.
In order to have it visible in the editor and compile I had to remove the Deprecated specifier from the BlueprintSCSHookData classes. Then, to make it so values could not be changed I had to make them all VisibleDefaultsOnly.
=> Update BlueprintSCSHooks to fix clearing data

Mods/Alpakit/Source/Alpakit/Private/AlpakitModEntryList.cpp, Mods/Alpakit/Source/Alpakit/Public/AlpakitModEntryList.h, Mods/Alpakit/Source/Alpakit/Public/AlpakitSettings.h
Refactor of the AlpakitModEntryList Slate code to make it modular and more readable.
Added a Combo Box for sorting by Friendly Name or Mod Reference. The selected value is saved/loaded automatically.
=> Refactor AlpakitModEntryList and add Sort Options

Mods/SML/Source/SML/Public/Settings/StringValueSelector.h
Fix for 
Happens when rapidly switching between two or more different string session options
it seems 1.1 header introduced this new method that must be overwritten in child classes
```cpp
virtual bool ShouldFocusOptionSlotToEdit() const
{
checkNoEntry();
return false;
}
```
Thanks to @mklierman for finding the solution
=> Fix crash when switching between string session settings

Source/FactoryGame/Private/FGSchematic.cpp
when the schematic is not actually a milestone and thus does not require an icon
=> Fixed validation from incorrectly throwing errors
